"""
send_report.py
Reads summary.json + dashboard.html → sends email with attachment.
All mail config read from environment variables (set in .gitlab-ci.yml).
Fails gracefully — never breaks the pipeline on mail errors.
"""

import os
import json
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text      import MIMEText
from email.mime.base      import MIMEBase
from email               import encoders
from datetime            import datetime
from pathlib             import Path

OUTPUT_DIR    = os.environ.get("OUTPUT_DIR",    "reports")
SUMMARY_PATH  = f"{OUTPUT_DIR}/summary.json"
DASHBOARD_PATH= f"{OUTPUT_DIR}/dashboard.html"

# Mail config — all from .gitlab-ci.yml variables
MAIL_TO             = os.environ.get("MAIL_TO",             "")
MAIL_CC             = os.environ.get("MAIL_CC",             "")
MAIL_SUBJECT_PREFIX = os.environ.get("MAIL_SUBJECT_PREFIX", "Perf Report")
SEND_MAIL_ON        = os.environ.get("SEND_MAIL_ON",        "always")   # always | fail_only | pass_only
TEST_NAME           = os.environ.get("TEST_NAME",           "Performance Test")

# SMTP config — from GitLab protected variables
SMTP_HOST = os.environ.get("SMTP_HOST", "")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASS = os.environ.get("SMTP_PASSWORD", "")
SMTP_SSL  = os.environ.get("SMTP_SSL", "false").lower() == "true"


# ══════════════════════════════════════════════════════════════════════════════
# 1. SHOULD WE SEND?
# ══════════════════════════════════════════════════════════════════════════════

def should_send(overall_result):
    if SEND_MAIL_ON == "always":
        return True
    elif SEND_MAIL_ON == "fail_only" and overall_result == "FAIL":
        return True
    elif SEND_MAIL_ON == "pass_only" and overall_result == "PASS":
        return True
    return False


# ══════════════════════════════════════════════════════════════════════════════
# 2. BUILD EMAIL CONTENT
# ══════════════════════════════════════════════════════════════════════════════

def build_subject(summary):
    result = summary["overall_result"]
    date   = datetime.now().strftime("%Y-%m-%d")
    icon   = {"PASS": "✅", "PARTIAL PASS": "⚠️", "FAIL": "❌"}.get(result, "")
    return f"[{result}] {icon} {MAIL_SUBJECT_PREFIX} — {TEST_NAME} | {date}"


def build_body(summary):
    result     = summary["overall_result"]
    score      = summary["perf_score"]
    grade      = summary["perf_grade"]
    stab       = summary["stab_score"]
    stab_st    = summary["stab_status"]
    total      = summary["total"]
    passed     = summary["passed"]
    partial    = summary["partial"]
    failed     = summary["failed"]
    avg_rt     = summary["avg_rt"]
    avg_tph    = summary["avg_tph"]
    avg_err    = summary["avg_error_pct"]
    generated  = summary["generated_at"]
    grafana    = summary.get("grafana_url", "")

    # Top failed transactions
    top_failed = [t for t in summary["transactions"] if t["overall_status"] == "RED"][:3]
    failed_lines = ""
    for t in top_failed:
        failed_lines += (
            f"\n    • {t['name']}"
            f" | P90: {t['p90_rt']}ms (target: {t['rt_target']}ms)"
            f" | TPH: {t['tph']} (target: {t['tph_target']})"
            f" | Error%: {t['error_pct']}%"
        )
    if not failed_lines:
        failed_lines = "\n    None"

    grafana_line = f"\n  Grafana Dashboard : {grafana}" if grafana else ""

    body = f"""
Performance Test Report — {TEST_NAME}
Generated: {generated}
{'='*60}

OVERALL RESULT   : {result}
Performance Score: {score}/100  (Grade: {grade})
Stability Score  : {stab}/100   ({stab_st})

TRANSACTION SUMMARY
  Total            : {total}
  ✅ Passed        : {passed}
  ⚠️  Partial Pass  : {partial}
  ❌ Failed        : {failed}

KEY METRICS
  Avg Response Time : {avg_rt} ms
  Avg Throughput    : {avg_tph} TPH
  Avg Error Rate    : {avg_err}%

TOP FAILED TRANSACTIONS:{failed_lines}
{grafana_line}
{'='*60}
Full performance dashboard is attached to this email.
Open the HTML file in any browser for the complete report
including charts, SLA comparison, error analysis, AI insights
and recommendations.
{'='*60}
This report was auto-generated by the Performance Framework.
LTIMindtree — Performance Engineering
"""
    return body.strip()


# ══════════════════════════════════════════════════════════════════════════════
# 3. SEND EMAIL
# ══════════════════════════════════════════════════════════════════════════════

def send_email(summary):
    if not MAIL_TO:
        print("[send_report] MAIL_TO not set — skipping email")
        return

    if not SMTP_HOST:
        print("[send_report] SMTP_HOST not set — skipping email")
        return

    to_list  = [addr.strip() for addr in MAIL_TO.split(",") if addr.strip()]
    cc_list  = [addr.strip() for addr in MAIL_CC.split(",") if addr.strip()] if MAIL_CC else []
    all_rcpt = to_list + cc_list

    msg = MIMEMultipart()
    msg["From"]    = SMTP_USER
    msg["To"]      = ", ".join(to_list)
    msg["CC"]      = ", ".join(cc_list)
    msg["Subject"] = build_subject(summary)

    msg.attach(MIMEText(build_body(summary), "plain"))

    # Attach dashboard.html
    if Path(DASHBOARD_PATH).exists():
        with open(DASHBOARD_PATH, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())
        encoders.encode_base64(part)
        filename = f"performance_dashboard_{datetime.now().strftime('%Y%m%d_%H%M')}.html"
        part.add_header("Content-Disposition", f'attachment; filename="{filename}"')
        msg.attach(part)
        print(f"[send_report] Attached : {filename}")
    else:
        print(f"[send_report] Dashboard not found at {DASHBOARD_PATH} — sending without attachment")

    try:
        if SMTP_SSL:
            server = smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT)
        else:
            server = smtplib.SMTP(SMTP_HOST, SMTP_PORT)
            server.starttls()

        if SMTP_USER and SMTP_PASS:
            server.login(SMTP_USER, SMTP_PASS)

        server.sendmail(SMTP_USER, all_rcpt, msg.as_string())
        server.quit()
        print(f"[send_report] Email sent to : {', '.join(all_rcpt)}")

    except Exception as e:
        # Never fail the pipeline for mail errors
        print(f"[send_report] Email failed (pipeline continues): {e}")


# ══════════════════════════════════════════════════════════════════════════════
# 4. MAIN
# ══════════════════════════════════════════════════════════════════════════════

def main():
    print(f"[send_report] Reading summary : {SUMMARY_PATH}")

    with open(SUMMARY_PATH) as f:
        summary = json.load(f)

    overall_result = summary["overall_result"]
    print(f"[send_report] Overall Result  : {overall_result}")
    print(f"[send_report] SEND_MAIL_ON    : {SEND_MAIL_ON}")

    if should_send(overall_result):
        send_email(summary)
    else:
        print(f"[send_report] Mail skipped — condition '{SEND_MAIL_ON}' not met for result '{overall_result}'")


if __name__ == "__main__":
    main()
